name = "Shrug"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a475c50239cdf3db7ce433349092c51f864b25c56e8b2f18cc5f94fef8bdf02"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.215"

[options]
acceptable-game-versions = ["1.21"]
